const currencyInfo={USD:['$','US dollar','美元'],EUR:['€','Euro','欧元'],GBP:['£','Pound sterling','英镑'],JPY:['¥','Japanese yen','日元']};
const from=document.querySelector('#from-currency'),to=document.querySelector('#to-currency');
function updatePair(changed){if(from.value===to.value){const other=changed===from?to:from;other.value=Object.keys(currencyInfo).find(c=>c!==changed.value);}for(const [side,el]of [['from',from],['to',to]]){const info=currencyInfo[el.value];document.querySelector('#'+side+'-code').textContent=el.value;document.querySelector('#'+side+'-symbol').textContent=info[0];document.querySelector('#'+side+'-name').textContent=info[document.documentElement.lang==='en'?1:2];}document.querySelector('.pair-output').innerHTML=from.value+' <span>→</span> '+to.value;}
from.addEventListener('change',()=>updatePair(from));to.addEventListener('change',()=>updatePair(to));document.querySelector('#swap-currencies').addEventListener('click',()=>{[from.value,to.value]=[to.value,from.value];updatePair();});
const scenarios={business:{en:['Payments with a business purpose.','Supplier invoices and overseas business expenses each come with their own context. Use your enquiry to explain the underlying payment need.',['Invoice or payment purpose','Beneficiary name and destination','Amount, currency and desired timing']],zh:['让企业付款，更有条理。','供应商发票与海外业务支出，各有不同背景。咨询时说明付款需求，有助于明确下一步需要了解的信息。',['发票或付款用途','收款人名称与目的地','金额、币种与预期时间']]},personal:{en:['For the people and plans that matter.','Whether your enquiry concerns family support, education or personal expenses abroad, start with the purpose and destination.',['General purpose of the transfer','Destination and receiving currency','Approximate amount and timing']],zh:['连接重要的人与计划。','无论是家庭支持、教育还是海外个人支出的咨询，都可以先从用途与目的地说起。',['汇款的一般用途','目的地与收款币种','大致金额与时间安排']]},currency:{en:['Start with the currency you need.','A clear currency requirement makes the conversation more useful. Discuss the amount, timing and how the applicable rate and charges will be confirmed.',['Original and target currencies','Intended amount and timing','Rate and total-cost enquiries']],zh:['从需要的币种开始。','清晰的币种需求，让沟通更加有效。说明金额与时间安排，并了解适用汇率与费用的确认方式。',['原币种与目标币种','预期金额与时间','汇率与整体费用咨询']]}};
let activeScene='business';function renderScene(){const d=scenarios[activeScene][document.documentElement.lang==='en'?'en':'zh'];document.querySelector('#scene-title').textContent=d[0];document.querySelector('#scene-text').textContent=d[1];document.querySelector('#scene-list').replaceChildren(...d[2].map(t=>{let li=document.createElement('li');li.textContent=t;return li;}));document.querySelector('.scenario-index').textContent='0'+(Object.keys(scenarios).indexOf(activeScene)+1)+' / 03';document.querySelector('#scenario-panel').setAttribute('aria-labelledby','tab-'+activeScene);}
const tabs=[...document.querySelectorAll('[data-scene]')];function selectTab(tab){activeScene=tab.dataset.scene;tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1;});renderScene();}tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();selectTab(tabs[n]);tabs[n].focus();}});});
window.addEventListener('languagechange',()=>{updatePair();renderScene();});updatePair();renderScene();
const reduced=matchMedia('(prefers-reduced-motion: reduce)');const toggle=document.querySelector('.motion-toggle');let paused=reduced.matches;function applyMotion(){document.body.classList.toggle('paused',paused);toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Play animations':'Pause animations');toggle.textContent=paused?'▷':'Ⅱ';}toggle.addEventListener('click',()=>{paused=!paused;applyMotion();});applyMotion();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.section-heading,.service-card,.exchange-copy,.exchange-stage,.steps article,.scenario-panel,.about-copy,.about-visual,.faq-list').forEach(el=>{el.classList.add('reveal');observer.observe(el);});let scheduled=false;function progress(){const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.width=(max?scrollY/max*100:0)+'%';scheduled=false;}addEventListener('scroll',()=>{if(!scheduled){requestAnimationFrame(progress);scheduled=true;}},{passive:true});progress();
